"""Reproduce the manually verified 18 September 2026 seed. Never run during updates."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
TODAY='2026-09-18'
rows=[]
def add(id,name,org,start,end,city,country,topics,url,deadline=None,state='unknown',series=None,event_quote='',deadline_quote='',notes='',time=None,zone=None):
 region='Oceania' if country=='Australia' else 'North America' if country=='United States' else 'Asia' if country=='Japan' else 'Europe'
 ev={'event_dates':{'url':url,'text':event_quote},'deadline':{'url':url,'text':deadline_quote} if deadline else None}
 call={'id':id+'-papers','kind':'Paper submission','deadline':deadline,'deadline_time':time,'deadline_timezone':zone,'state':state,'source_url':url,'evidence':ev['deadline']}
 rows.append(dict(id=id,series_id=series,name=name,organizers=[org],event_type='Workshop' if 'workshop' in name.lower() else 'Conference',event_start=start,event_end=end,city=city,country=country,region=region,topics=topics,source_url=url,event_state='announced',calls=[call],notes=notes,discovered_at=TODAY,last_checked=TODAY,last_verified=TODAY,verification_method='manual primary-source review',health='verified',evidence=ev,history=[]))
C='https://cepr.org/events/'
N='https://www.nber.org/'
add('cepr-heterogeneity-2026','Macroeconomic Policies with Heterogeneous Agents (3rd edition)','CEPR / Paris School of Economics','2026-12-15','2026-12-16','Paris','France',['Heterogeneous agents','Monetary policy','Fiscal policy'],C+'macroeconomic-policies-heterogeneous-agents-3rd-edition','2026-09-20','open','cepr-heterogeneity','15 Dec 2026 - 16 Dec 2026','Closes 20 September 2026 at 23:59',time='23:59',notes='Papers or extended abstracts. Source gives a cutoff time but no time zone.')
add('nber-isom-2027','50th International Seminar on Macroeconomics','NBER / Central Bank of Montenegro','2027-06-18','2027-06-19',None,'Montenegro',['International macro'],N+'50th-annual-international-seminar-macroeconomics','2026-11-01','open','nber-isom','June 18-19, 2027','by November 1, 2026',notes='Detailed abstract or draft paper. Submissions must not be under consideration at another journal; submission includes consideration for a JIE special issue.')
add('nber-hf-2026','Household Finance Working Group Meeting, Fall 2026','NBER','2026-12-11',None,'Cambridge, MA','United States',['Household finance'],N+'conferences/household-finance-working-group-meeting-fall-2026','2026-10-08','open','nber-hf','December 11, 2026','11:59 pm Eastern time on October 8, 2026',time='23:59',zone='America/New_York',notes='Open paper submission; attendance is by invitation.')
add('franco-german-fiscal-2026','Franco-German Fiscal Policy Seminar','German and French finance ministries','2026-12-01','2026-12-02','Berlin','Germany',['Fiscal policy','Growth'],C+'2026-franco-german-fiscal-policy-seminar','2026-10-09','open','franco-german-fiscal','1 Dec 2026 - 2 Dec 2026','submitted by 9 October 2026',notes='Theme: artificial intelligence, productivity and public finances. Papers in English.')
add('nber-demographics-2027','Demographic Forces and US Labor Market Dynamics','NBER','2027-03-05',None,'San Francisco, CA','United States',['Labour macro','Pensions and retirement'],N+'calls-papers-and-proposals/demographic-forces-and-us-labor-market-dynamics','2026-12-01','open',None,'March 5, 2027','11:59pm ET on Tuesday, December 1, 2026',time='23:59',zone='America/New_York')
add('nber-tariffs-2027','Tariffs and Economic Performance','NBER','2027-04-01',None,'Cambridge, MA','United States',['International macro'],N+'conferences/tariffs-and-economic-performance-spring-2027','2026-12-16','open',None,'April 1, 2027','11:59 pm Eastern time on December 16, 2026',time='23:59',zone='America/New_York')
add('nber-labor-power-2027','Measuring and Modeling Market Power in the Labor Market','NBER','2027-05-14',None,'Cambridge, MA','United States',['Labour macro'],N+'calls-papers-and-proposals/measuring-and-modeling-market-power-labor-market',None,'unknown',None,'Friday, May 14, 2027',notes='Call listed by NBER. Deadline will be confirmed from the dedicated source before publication.')
add('sed-2027','Society for Economic Dynamics Annual Meeting','SED / Católica Lisbon','2027-07-01','2027-07-03','Lisbon','Portugal',['General macro','Growth','Heterogeneous agents'], 'https://economicdynamics.org/',None,'not_yet_open','sed','July 1-3 in Lisbon, Portugal',notes='2027 meeting announced; call for papers forthcoming.')
add('res-2027','Royal Economic Society Annual Conference','Royal Economic Society','2027-06-28','2027-06-30','Reading','United Kingdom',['General macro'],'https://res.org.uk/event-listing/res2027/','2027-01-18','not_yet_open','res','Monday 28 – Wednesday 30 June 2027','18 January 2027',time='23:55',zone='Europe/London',notes='General paper submissions open in October 2026. Broad economics conference.')
rows[-1]['calls'][0]['kind']='General sessions'
rows[-1]['calls'].append(dict(id='res-2027-posters',kind='Speed / poster sessions',deadline='2027-04-12',deadline_time='23:55',deadline_timezone='Europe/London',state='not_yet_open',source_url=rows[-1]['source_url'],evidence={'url':rows[-1]['source_url'],'text':'12 April 2027'}))
add('cepr-hf-2026','CEPR European Conference on Household Finance','CEPR / Study Center Gerzensee','2026-10-07','2026-10-09','Bern / Gerzensee','Switzerland',['Household finance'],C+'cepr-european-conference-household-finance-2026','2026-06-18','closed','cepr-hf','7 Oct 2026 - 9 Oct 2026','Thursday 18 June 2026',notes='Policy event in Bern on 7 October; research conference in Gerzensee on 8–9 October.')
add('cepr-mef-2026','CEPR Monetary Economics and Fluctuations Symposium','CEPR','2026-10-05','2026-10-07','Gerzensee','Switzerland',['Monetary policy','Business cycles'],C+'event-series/monetary-economics-and-fluctuations-programme-annual-meeting/cepr-annual-0',None,'closed','cepr-mef','5 Oct 2026 - 7 Oct 2026',notes='Source states submissions are closed.')
add('cepr-imf-2026','CEPR International Macroeconomics and Finance Programme Meeting','CEPR','2026-11-02','2026-11-03','Gerzensee','Switzerland',['International macro','Macro-finance'],C+'cepr-international-macroeconomics-and-finance-imf-programme-meeting-2026','2026-05-31','closed','cepr-imf','2 Nov 2026 - 3 Nov 2026','Sunday 31 May 2026 (23:59 BST)',time='23:59',zone='Europe/London')
add('cepr-mg-2026','CEPR Macroeconomics and Growth Annual Symposium','CEPR / CUNEF','2026-11-19','2026-11-20','Madrid','Spain',['Growth','Heterogeneous agents'],C+'cepr-macroeconomics-and-growth-annual-symposium-2026','2026-06-30','closed','cepr-mg','19 Nov 2026 - 20 Nov 2026','Tuesday 30th June 2026, 18:00 CEST',time='18:00',zone='Europe/Madrid')
add('cepr-ireland-2026','Macro-Finance and Financial Stability Policies','Central Bank of Ireland / UCD / CEPR','2026-11-30','2026-12-01','Dublin','Ireland',['Macro-finance','Financial stability'],C+'central-bank-ireland-ucd-cepr-conference-macro-finance-and-financial-stability-policies-2026','2026-06-23','closed','cepr-ireland','30 Nov 2026 - 1 Dec 2026','submitted by 23 June 2026')
add('cepr-empirical-monetary-2026','Workshop on Empirical Monetary Economics','OFCE / CEPR','2026-12-01','2026-12-02','Paris','France',['Monetary policy','Heterogeneous agents'],C+'workshop-empirical-monetary-economics-2026','2026-09-15','closed','empirical-monetary','1 Dec 2026 - 2 Dec 2026','Submission deadline: 15 September 2026')
add('cepr-paris-2026','CEPR Paris Symposium','CEPR','2026-12-03','2026-12-08','Paris','France',['General macro'],C+'event-series/cepr-paris-symposium/cepr-paris-symposium-2026',None,'closed','cepr-paris','3 Dec 2026 - 8 Dec 2026',notes='Paper and poster submissions under review. Poster eligibility differs from paper eligibility.')
add('cepr-finland-2026','Navigating Monetary Policy by the Northern Lights','Bank of Finland / CEPR','2026-12-17','2026-12-18','Saariselkä','Finland',['Monetary policy','Heterogeneous agents'],C+'bank-finland-and-cepr-joint-conference-navigating-monetary-policy-northern-lights',None,'closed','cepr-finland','17 Dec 2026 - 18 Dec 2026',notes='Attendance limited to presenters. Source contains an old notification year; no deadline inferred.')
add('steg-2027','STEG Annual Conference and Theme Workshops','CEPR / STEG','2027-01-06','2027-01-09','Manchester','United Kingdom',['Growth'],C+'steg-annual-conference-theme-workshops-2027',None,'closed','steg','6 Jan 2027 - 9 Jan 2027',notes='Research on structural transformation and growth in low-income countries; source states submissions are closed.')
add('rba-quant-2026','RBA Quantitative Macroeconomics Workshop','Reserve Bank of Australia','2026-12-09','2026-12-11','Sydney','Australia',['General macro','International macro','Computational macro'],'https://www.rba.gov.au/publications/workshops/research/','2026-08-28','closed','rba-quant','9–11 December 2026','Friday, 28 August 2026')
add('rba-cem-2026','Continuing Education in Macroeconometrics Workshop','RBA / SNDE / CAMA','2026-11-17','2026-11-18','Sydney','Australia',['Computational macro','Business cycles'],'https://www.rba.gov.au/publications/workshops/continuing-education-macroeconometrics/2026/','2026-07-31','closed','cem','17–18 November 2026','Deadline: July 31, 2026',notes='Includes contributed research papers as well as masterclasses.')
add('nber-macroannual-2027','NBER Annual Conference on Macroeconomics','NBER','2027-04-29','2027-04-30','Cambridge, MA','United States',['General macro'],N+'conferences/annual-conference-macroeconomics-2027',None,'unknown','nber-macroannual','April 29-30, 2027',notes='Attendance by invitation. No open submission call verified.')
add('nber-deficits-2027','Long-Term Budget Deficits: Economic Effects and Potential Responses','NBER','2027-05-20','2027-05-21','Washington, DC','United States',['Fiscal policy','Macro-finance'],N+'calls-papers-and-proposals/call-papers-long-term-budget-deficits-economic-effects-and-potential-responses','2026-08-31','closed',None,'May 20–21, 2027','11:59 pm ET on Monday, August 31, 2026',time='23:59',zone='America/New_York')
add('nber-energy-2026','Energy Markets and the Macroeconomy','NBER','2026-12-10','2026-12-11','Cambridge, MA','United States',['Business cycles'],N+'conferences/energy-markets-and-macroeconomy-fall-2026',None,'closed',None,'December 10-11, 2026',notes='Source states the submission deadline has passed.')
add('nber-ifm-2026','International Finance and Macroeconomics Program Meeting','NBER','2026-10-23',None,'Cambridge, MA','United States',['International macro'],N+'conferences/international-finance-and-macroeconomics-program-meeting-fall-2026',None,'unknown','nber-ifm','October 23, 2026',notes='Attendance by invitation. No open submission call verified.')
add('imf-polak-2026','Jacques Polak Annual Research Conference','International Monetary Fund','2026-11-12','2026-11-13','Washington, DC','United States',['International macro','Growth'],'https://www.imf.org/en/news/seminars/conferences/2026/11/12/2026-jacques-polak-annual-research-conference',None,'unknown','imf-polak','November 12-13, 2026',notes='Theme: technology, geopolitics and a multipolar world. Submission status unconfirmed.')
for r in rows:
 (ROOT/'data/evidence'/f'{r["id"]}.json').write_text(json.dumps({'checked_on':TODAY,'method':r['verification_method'],'evidence':r['evidence']},ensure_ascii=False,indent=2)+'\n')
(ROOT/'data/conferences.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
print(f'Seeded {len(rows)} verified events')
